version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - XERO_MOCK_URL=http://xero-mock:3000
    depends_on:
      xero-mock:
        condition: service_healthy

  xero-mock:
    image: jaypeng2015/show-me-the-money
    ports:
      - "3001:3000"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:3000/api.xro/2.0/Reports/BalanceSheet",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  default:
    name: app-network
    driver: bridge
